version: '3.8'

services:
  db_st:
    image: postgres:15.5
    container_name: db_st_container
    env_file:
      - ./conf/db/.db.env
    ports:
      - "5438:5432"
    volumes:
      - db_st_data:/var/lib/postgresql/data
    networks:
      backend_network:
    restart: on-failure
  rabbitmq_st:
    image: rabbitmq:3-management
    container_name: rabbitmq_st
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      backend_network:
    restart: on-failure
  api_st:
    build:
      context: .
      dockerfile: Dockerfile
    image: simple-talking-image
    container_name: api_st
    depends_on:
      - db_st
      - rabbitmq_st
    ports:
      - "8080:8081"
    networks:
      - backend_network
    restart: on-failure

volumes:
  db_st_data:

networks:
  backend_network:
